services:
  db:
    container_name: quotient_database
    image: postgres
    restart: always
    env_file:
      - .env
    networks:
      - quotient_network

  server:
    container_name: quotient_server
    image: quotient_server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      - quotient_network
    volumes:
      - ./submissions:/app/submissions
      - ./config:/app/config
      - ./engine:/app/engine
      - ./static:/app/static

  redis:
    image: redis:alpine
    container_name: quotient_redis
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - quotient_network
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"]

  runner:
    build:
      context: .
      dockerfile: Dockerfile.runner
    deploy:
      mode: replicated
      replicas: 10 # Adjust based on server resources
    restart: always
    privileged: true
    env_file:
      - .env
    depends_on:
      - redis
      - db
    networks:
      - quotient_network
    volumes:
      - ./submissions:/app/submissions
      - ./custom-checks:/app/checks
    tmpfs:
      - /tmp:size=32m
        #dns:
        #- 10.128.0.26

  divisor:
    build:
      context: divisor/
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    network_mode: host # Use host networking for divisor
    depends_on:
      - redis
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  quotient_network:
    driver: bridge

